### ISSUE TITLE
Device - GetInterfaces

### ISSUE THREAD

**Issue by broberts-nybble** [altera2015/usbserial#17]
Is it possible to expose the call to list the device interfaces?

**Comment by broberts-nybble** [comment]
yes please

**Comment by MysthawkCanada** [comment]
I currently have a device that has 3 interfaces on a single serial port, the 'getInterfaceCount' would help so that I know how many items I would have to loop through.  Ideally though we could have more information when the 'listDevices' returns its list of devices.

Is there any chance this feature would be looked at and potentially implemented?

Thanks for your time!
Michael

**Comment by altera2015** [comment]
I've added this as a UsbDevice.interfaceCount property. (release upcoming)
